### ISSUE TITLE
Chat server crashes after page refresh

### ISSUE THREAD

**Issue by illarion** [oleyansen/node-chat-example#1]
Steps to reproduce:
1. Start a chat server
2. Use it for some time
3. Press F5 (refresh) in the browser

AR: server crashes with:
```
node-chat-example/node_modules/ws/lib/websocket.js:328
      throw err;
      ^

Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/shaman/workspace/teradek/node-chat-example/node_modules/ws/lib/websocket.js:322:19)
    at RedisClient.<anonymous> (/home/shaman/workspace/teradek/node-chat-example/chat-server.js:47:8)
    at emitTwo (events.js:131:20)
    at RedisClient.emit (events.js:214:7)
    at return_pub_sub (/home/shaman/workspace/teradek/node-chat-example/node_modules/redis/index.js:786:18)
    at RedisClient.return_reply (/home/shaman/workspace/teradek/node-chat-example/node_modules/redis/index.js:833:9)
    at JavascriptRedisParser.returnReply (/home/shaman/workspace/teradek/node-chat-example/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/shaman/workspace/teradek/node-chat-example/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/shaman/workspace/teradek/node-chat-example/node_modules/redis/index.js:274:27)
    at emitOne (events.js:116:13)
```

ER: chat works

**Comment by illarion** [comment]
The fix is challenging: the obvious solution could lead to memory leaks

**Comment by oleyansen** [comment]
Added check for alive ws channels before publish to Redis and send to ws
